version: '3.7'
networks:
  gateway: {}
services: 
  postgres:
    restart: always
    image: mutemath966/pgbouncer:0.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
      PGDATA: /postgres/data
      BACKUPTIME: "04:00:00"
    container_name: postgres
    networks:
      - gateway
    ports:
      - "6432"
    volumes:
      - "./pgdata:/postgres/data"
      - "./pgbouncer_confFiles/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
      - "./pgbouncer_confFiles/userlist.txt:/etc/pgbouncer/userlist.txt"
    command: postgres -N 500