version: '3.7'
networks:
  gateway: {}
services:
  postgres:
    restart: always
    image: mutemath966/postgres_backup:0.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
      PGDATA: /postgres/data
      BACKUPTIME: "04:00:00"
    container_name: postgres
    networks:
      - gateway
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/postgres/data"