version: '3.7'
services:
  postgresql-master:
    image: mutemath966/pgbouncer:0.2
    ports:
      - '5432'
    volumes:
      - './backups:/postgres/data'
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: testdb
      ALLOW_EMPTY_PASSWORD: "yes"
      BACKUPTIME: "00:22:00"
      PGDATA: /postgres/data
  postgresql-slave:
    image: mutemath966/pgbouncer:0.2
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_HOST: postgresql-master
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  backups:
